[package]
org = "xlibb"
name = "pipe"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["pipe"]
repository = "https://github.com/xlibb/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"
icon = "icon.png"

[[platform.java21.dependency]]
groupId = "io.xlibb.pipe"
artifactId = "pipe-native"
version = "@toml.version@"
path = "../native/build/libs/pipe-native-@project.version@.jar"
