name: Publish to the Ballerina central

on:
    workflow_dispatch:

jobs:
    publish-release:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'xlibb'
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Set up JDK 21
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: 21.0.3

            -   name: Build with Gradle
                env:
                    packageUser: ${{ github.actor }}
                    packagePAT: ${{ secrets.GITHUB_TOKEN }}
                run: ./gradlew build -x check -x test

            -   name: Create lib directory if not exists
                run: mkdir -p ballerina/lib

            -   name: Run Trivy vulnerability scanner
                uses: aquasecurity/trivy-action@master
                with:
                    scan-type: "rootfs"
                    scan-ref: "${{ github.workspace }}/ballerina/lib"
                    format: "table"
                    timeout: "10m0s"
                    exit-code: "1"
                    scanners: "vuln"

            -   name: Publish artifact
                env:
                    BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
                    packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                    packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
                run: ./gradlew clean build -PpublishToCentral=true
